#!/bin/bash

#display -window root ~/Pictures/Wallpapers/debian_minimal.png
display -window root ~/Pictures/Wallpapers/minimal_mountains1080.png

setxkbmap -option compose:ralt

trayer \
   --expand true \
   --edge top --align right --margin 225 \
   --widthtype request --height 30 \
   --transparent true --alpha 0 --tint 0x424242 &

xscreensaver &
#pulseaudio --start 
ibus-daemon --replace &

volumeicon &
#glista &

urxvtd -q -f -o


sleep 1 && ~/.local/bin/limebar2 &

exec ~/Code/Git/simplewm/simplewm
