#!/bin/sh
#
# fluxbox startup-script:
#
# Lines starting with a '#' are ignored.

display -window root ~/Pictures/Wallpapers/debian_minimal.png

setxkbmap -option compose:ralt

exec fluxbox &
fbpid=$!

{
   trayer \
      --expand true \
      --edge top --align right --margin 178 \
      --widthtype request --height 30 \
      --transparent true --alpha 0 --tint 0x424242 &

   pulseaudio --start
   ibus-daemon &

   sleep 1

   volumeicon &

   urxvtd -q -f -o

   ~/.local/bin/limebar &
} &

wait $fbpid

# or if you want to keep a log:
# exec fluxbox -log "/home/rueno/.fluxbox/log"
