#!/bin/sh
# PekWM start file
# This file is a simple shell script; It gets run on pekwm startup, after 
# the theme and all config has loaded if it is set executable
# (chmod +x start).
#
# This is different from ~/.xinitrc because a normal configuration of 
# .xinitrc you'll run all commands, then launch the window manager last.
#
# It also gets re-run every time pekwm is restarted.
# 
# As for it's usefulness, well, it's up to you. I actually set my background
# from my start file; since it runs after the theme gets loaded, this 
# effectively overrides whatever's in the theme.
# 
# There's probably a few other good uses for it, too. I mainly pushed for it
# because when I was doing fluxbox's docs, people used to complain that there
# wasn't one, and I wanted to avoid that for pekwm. ;) --eyez

display -window root ~/Pictures/Wallpapers/debian_minimal.png

setxkbmap -option compose:ralt

trayer \
   --expand true \
   --edge top --align right --margin 178 \
   --widthtype request --height 30 \
   --transparent true --alpha 0 --tint 0x424242 &

sleep 1

volumeicon &
#glista &

urxvtd -q -f -o

~/.local/bin/limebar &
